global using System.Collections;
global using System.Collections.Immutable;
global using System.Numerics;
global using FluentAssertions;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using ToolBX.Dummies;
global using ToolBX.Dummies.Exceptions;
global using ToolBX.Dummies.Resources;
global using ToolBX.Mathemancy;